os: linux
language: generic
dist: focal

jobs:
  include:
    - stage: "Tests"
      name: "Create custom image"
      vm:
        create:
          name: cust-image-1605
    - stage: "Tests"
      name: "Create unique custom image"
      vm:
        create:
          name: job-unique
