os: linux
language: generic
dist: focal

vm:
  create:
    name: new-custom-image2

script:
  - sudo mkdir /my-custom-dir2
  - echo "Test custom image2!" | sudo tee /my-custom-dir/my_custom_file2.txt
  - sudo cat /my-custom-dir2/my_custom_file2.txt
